// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbj7pH6pMWVdF7glY7DN8kLjGAFqvozxM',
    appId: '1:660932455666:web:e4b8eca7654e683112346b',
    messagingSenderId: '660932455666',
    projectId: 'kltn-64a61',
    authDomain: 'kltn-64a61.firebaseapp.com',
    storageBucket: 'kltn-64a61.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ABrWjX4DYcddBS24G1WH85Bf6ryk-0U',
    appId: '1:660932455666:android:f4d86540f1ef233312346b',
    messagingSenderId: '660932455666',
    projectId: 'kltn-64a61',
    storageBucket: 'kltn-64a61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmTM9PWSzAYAxQTt9RuZbqTZ-osr4no_E',
    appId: '1:660932455666:ios:05003a005329fef912346b',
    messagingSenderId: '660932455666',
    projectId: 'kltn-64a61',
    storageBucket: 'kltn-64a61.firebasestorage.app',
    iosBundleId: 'com.example.mcqgenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmTM9PWSzAYAxQTt9RuZbqTZ-osr4no_E',
    appId: '1:660932455666:ios:05003a005329fef912346b',
    messagingSenderId: '660932455666',
    projectId: 'kltn-64a61',
    storageBucket: 'kltn-64a61.firebasestorage.app',
    iosBundleId: 'com.example.mcqgenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbj7pH6pMWVdF7glY7DN8kLjGAFqvozxM',
    appId: '1:660932455666:web:5bd6aecee394ca1012346b',
    messagingSenderId: '660932455666',
    projectId: 'kltn-64a61',
    authDomain: 'kltn-64a61.firebaseapp.com',
    storageBucket: 'kltn-64a61.firebasestorage.app',
  );
}
